### PR TITLE
Don't fail on err in exec

### LINKED ISSUE #258: `otel-cli exec` does not report a span if the command failed
```sh
$ otel-cli exec -- false
```

The above example does not report a span. If I run with `--verbose`, then I see this:

```sh
$ otel-cli exec --verbose -- false
2023/08/30 18:36:07 command failed: exit status 1
```

I think the issue is [here](https://github.com/equinix-labs/otel-cli/blob/5f1223a809007b088af2ea9b9c534a798589f1f4/otelcli/exec.go#L96-L99):

```go
	if err := child.Run(); err != nil {
		config.SoftFail("command failed: %s", err)
	}
	span.EndTimeUnixNano = uint64(time.Now().UnixNano())

	ctx, err := otlpclient.SendSpan(ctx, client, config, span)
	if err != nil {
		config.SoftFail("unable to send span: %s", err)
	}
```

Calling `config.SoftFail` is going to exit immediately. What is probably intended instead is to record the span with an error code.

### PR DESCRIPTION
**Pull request by parsonsmatt**
Fixes #258 

I'm having a hard time writing a test for this. I have verified that this change makes the code do what I want - spans show up in Honeycomb and `otel-cli exec false` has a non-0 exit code.

```
λ otel-cli exec --name "false" false
λ echo $?
1
```

However, the test does not appear to work? Locally it tells me that no spans were recorded.

### CODE REVIEW

File: otelcli/exec.go [hunk 1]
```diff
@@ -94,7 +95,10 @@ func doExec(cmd *cobra.Command, args []string) {
 	}
 
 	if err := child.Run(); err != nil {
-		config.SoftFail("command failed: %s", err)
+                span.Status = & tracev1.Status {
+                        Message: fmt.Sprintln("exec command failed: ", err),
```
Comment (tobert) [inline otelcli/exec.go:99]: I'd just do fmt.Sprintf here, message doesn't need the newline.

File: data_for_test.go [hunk 2]
```diff
@@ -369,6 +369,23 @@ var suites = []FixtureSuite{
...
+        //                 Expect: Results{
+        //                         SpanCount: 1,
+        //                         CliOutput: "",
+        //                         Diagnostics: otelcli.Diagnostics{
+        //                                 ExecExitCode: 1,
+        //                         },
+	// 			Config:    otelcli.DefaultConfig().WithEndpoint("grpc://{{endpoint}}"),
+        //                 },
+        //         },
+        // },
```
Comment (tobert) [inline data_for_test.go:388]: Hmmm this test looks right.

Try adding `"--fail", "--verbose"` to the CliArgs. It looks like `config.SoftFail` is being called when child.Run() returns an err.

> If the command starts but does not complete successfully, the error is of type *ExitError. Other error types may be returned for other situations.

so the `if err :- child.Run(); err != nil` needs to be expanded to check for ExitError and not SoftFail on that so you can send the error upstream in the span status.

**Review by tobert — CHANGES_REQUESTED** [review]
If you have time to work on this, I've provided some notes that should help you make progress. If you don't have time, LMK and I'll finish it up.

**Comment by parsonsmatt** [comment]
Unfortunately, I don't have further cycles to put towards this. Thanks for the review and the time/effort you've spent on this tool!

**Comment by tobert** [comment]
Thanks for the PR! Work is busy right now so it might take me a couple weeks but I'll get this in and release.

**Review by tobert — APPROVED** [review]
Thanks for getting this started!

It turned out the test code that examines exit status needed some rework to test this, so I added that to your PR.
